### ISSUE TITLE
Voto null e punteggio non assegnato ad ogni domanda

### ISSUE THREAD

**Issue by SpanishInquisition49** [samul-1/sai_training_frontend#1]
Spero che sia la repository giusta per segnalarlo:
Al termine di un esercitazione non viene assegnato nessun punteggio nonostante ogni domanda abbia una risposta selezionata
![image](https://user-images.githubusercontent.com/71408527/182182418-e0cdf053-3fc9-4ed3-8d73-286b0e75b609.png)

**Comment by samul-1** [comment]
Ciao, il repo per Evo è questo: https://github.com/samul-1/sai_evo_frontend
comunque grazie per la segnalazione.

È un bug introdotto con l'ultimo aggiornamento, a breve verrà corretto. Per ora puoi basarti sulle x/tick accanto alle risposte per sapere quante ne hai fatte giuste.
